#!/bin/sh
PC="/etc/prescient.conf"
repo=${PWD##*/}
while read oval commit ref; do
  if [ '0000000000000000000000000000000000000000' = "$commit" ]; then continue; fi
  # try to get .prescient from tree
  tmp_dir=`mktemp -d /tmp/prescient-XXXXX`
  mkdir "${tmp_dir}/tree"
  git clone -q -n $GIT_DIR "${tmp_dir}/tree" >/dev/null 2>/dev/null
  unset GIT_DIR
  cd "${tmp_dir}/tree"
  git checkout -q $commit >/dev/null 2>/dev/null
  if [ ! -f "${tmp_dir}/tree/.prescient" ]; then
    echo "No .prescient file found in tree of ${commit}, skipping CI."
  else
    # prepare repo
    cd $tmp_dir
    zip -1 -y -r -q "${tmp_dir}/tree.zip" tree
    machines=`grep -o -E "^[a-zA-Z0-9_-]+" "${tmp_dir}/tree/.prescient"` # security !!!
    for machine in $machines; do
      machine_line=`grep "${machine}|" ${PC} | shuf -n 1`
      if [ -z "$machine_line" ]; then
        echo "Can't enqueue CI run for $commit on '$machine'. No machine configuration for '$machine' found!"
      else
        host=`echo $machine_line | awk -F'|' '{print $2}'`
        user=`echo $machine_line | awk -F'|' '{print $3}'`
        vm=`echo $machine_line | awk -F'|' '{print $4}'`
        vm_user=`echo $machine_line | awk -F'|' '{print $5}'`
        vm_user_pass=`echo $machine_line | awk -F'|' '{print $6}' | tr -d '\r'`
        ci_vm="${vm}_Prescient"
        cm="${commit}_${machine}"
        cl_script="$tmp_dir/${cm}_copy_log" # at script
        macl_script="$tmp_dir/${cm}_cleanup_host"
        echo "Enqueueing CI run for $commit on '$machine'."
        ssh $user@$host mkdir -p '$HOME/.prescient'
        scp "${tmp_dir}/tree.zip" "$user@$host:~/.prescient/$cm.zip"
        ssh $user@$host ln -sf /var/lib/laminar/cfg/jobs/prescient.run /var/lib/laminar/cfg/jobs/${repo}.run
        ssh $user@$host laminarc queue ${repo} machine="${machine}" vm="${vm}" commit="${commit}" vm_user=${vm_user} vm_user_pass=${vm_user_pass}
        # cleanup everything else after 13 hours
        echo "rm -rf $tmp_dir" > "$tmp_dir/${cm}_remove_tmp"
        at -f "$tmp_dir/${cm}_remove_tmp" now + 13 hours 2>/dev/null
      fi
    done
  fi
done
exit 0
